---
title: 예외처리
date: 2018-10-31 00:00:40 +0900
tags:
  - java
---
## Exception 예외처리
- 예외 : 고객 혹은 가상머신(JVM)이 예상한 결과와 다르게 엉뚱한 값 혹은 행동이 발생하는 것.
- 입출력 예외처리에 대한 클래스를 가장 많이 구현해놓았다
 - 그 이유는 사용자가 어떻게 입력할지 예상을 할 수 없기 때문에 따라서 많은 경우들을 만들어놓았다.

- 에러에는 크게 두 가지가 있다.
 - 실행시 발생되는 에러
 - 문법적인 에러

- 사용자에게 메세지를 주고 사용자로 하여금 수정할수 있게 하기 위해 만들어졌다.
- 예외 처리를 하지 않을 경우 심각한 에러로 생각하고 프로그램을 실행할 수 없다.

### Runtime Exception
- 프로그램이 실행 중에 발생하게 된다. 처리하기 위해서는 Debugging을 통해서 원인을 찾고 변경해줘야한다.
- 고의적인 예외를 심어 놓음으로 예외가 발생했을 때 개발자가 상황에 맞게 처리해줘야한다.

### 일반적인 Exception
- 사용자의 실수와 같은 외적인 요인에 의해 발생되는 예외이다
- 그렇다면 어떻게 예외를 처리하는가?
  - try - catch 구문을 이용해서 사용한다.
  - 예외가 발생된 실행 구문 밑의 코드들은 실행하지 않는다.

```java
try{
  //예외가 발생할 것 같은 부분
  구문1
  구문2   <- 예외 발생(catch문으로 이동)
  구문3   <- 이하 코드들은 실행하지 않음
  구문4
}catch(Exception e){
  //예외가 발생했을 때 처리해주는 부분
}catch(Exception e2){

} finally{

}
```

- 왜 finally 구문이 필요한가?
  - 예외가 발생하더라도 **반드시 실행해야 하는 부분** (자원을 저장하는 부분, 사용하고 있는 자원들을 안전하게 처리하기 위하여)

- 다중 catch 문을 사용시에 주의사항 : 상위 구조가 위에 오면 안된다.
- Exception 을 쓰지 않고 해당 코드에 맞는 Exception을 사용하는 이유는 미세한 속도 차이가 있기 때문이다. 모든 Exception을 검사하는 것이 아니기 때문이다

```java
public class ExceptionEx2 {
	String str = "";

	public void foo(int i) {
		try {
			if(i == 1) {
				throw new Exception();
			}
			str += " 1 ";
		} catch(Exception e) {
			str += " 2 ";
			return;
		} finally {
			str += " 3 ";
		}
		str += " 4 ";
	}

	public static void main(String[] args) {
		ExceptionEx2 ee = new ExceptionEx2();
		ee.foo(0); //" 1  3  4 "
		ee.foo(1); //" 1  3  4  2  3 "
		System.out.println(ee.str);
	}
}
```

- 위의 예제를 보면 finally 구문을 반드시 실행하는 것을 알 수 있다.
- 그리고 마지막에 4가 붙지 않는 이유는 return 해주기 때문에 붙지 않는다.

### RuntimeEception
- 개발자의 실수로 발생하는 예외이다.
- 가장 많이 발생하는 예외는 배열의 범위를 넘어선 참조를 할 때 (ArrayIndexOutofBoundsException) 와 생성되지 않은 객체를 참조할때 발생되는 NullPointerException 등이 있다.
